# Generated by Django 4.1.3 on 2023-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_alter_daily_records_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_records',
            old_name='login_time',
            new_name='init_login',
        ),
        migrations.AddField(
            model_name='daily_records',
            name='login_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
