#!/bin/bash

# creating all the environment variables in a file
cat >.env_all<<EOF
export SECRET_KEY="$(openssl rand -hex 40)"
export PROJECT_HOME="$(pwd)"
export VIRTENV_LOC="$HOME/.virtenv/"
export VIRTENV_ACT_LOC="${VIRTENV_LOC}/bin/activate"
EOF

#source the above file
source .env_all

#  check if the required packages are installed or not
if [[ ! $(dpkg --get-selections | grep '^python3-pip.*install$') || ! $(dpkg --get-selections | grep '^virtualenv.*install$') || ! $(d
pkg --get-selections | grep '^python-is-python3.*install$') ]]
then
  sudo apt update && sudo apt install python-is-python3 python3-pip virtualenv -y
fi

# check if the virtualenv is installed
#if [ ! -d '~/env' ]
if [ ! -d ${VIRTENV_LOC} ]
then
        python -m virtualenv ${VIRTENV_LOC}
fi

pip install -r ${PROJECT_HOME}/requirements
nohup python ${PROJECT_HOME}/manage.py runserver 0.0.0.0:8000 &
