#!/bin/bash

# creating all the environment variables and copy to /etc/profile.d
cat >custom_env.sh<<EOF
export PROJECT_HOME="$(pwd)"
export SECRET_KEY="$(openssl rand -hex 40)"
export VIRTENV_HOME="$HOME/.virtenv"  #error: VIRTENV_HOME not exported so can't give value to below variables
#export VIRTENV_ACT="$VIRTENV_HOME/bin/activate"
export VIRTENV_ACT="$HOME/.virtenv/bin/activate"
EOF

# copy file to /etc/profile.d and source the above file
sudo cp custom_env.sh /etc/profile.d/
source /etc/profile

#  check if the required packages are installed or not
if [[ ! $(dpkg --get-selections | grep '^python3-pip.*install$') || ! $(dpkg --get-selections | grep '^virtualenv.*install$') || ! $(d
pkg --get-selections | grep '^python-is-python3.*install$') ]]
then
  sudo apt update && sudo apt install python-is-python3 python3-pip virtualenv -y
fi

# check if the virtualenv is installed
if [ ! -d ${VIRTENV_HOME} ]
then
        python -m virtualenv ${VIRTENV_HOME}
fi

source ${VIRTENV_ACT}
pip install -r ${PROJECT_HOME}/requirements
nohup python ${PROJECT_HOME}/manage.py runserver 0.0.0.0:8000 &
